//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OCAEntities : DbContext
    {
        public OCAEntities()
            : base("name=OCAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pub_Usuarios> Pub_Usuarios { get; set; }
        public virtual DbSet<tbl_Aceesos_Evento> tbl_Aceesos_Evento { get; set; }
        public virtual DbSet<tbl_Definicion_Opciones> tbl_Definicion_Opciones { get; set; }
        public virtual DbSet<tbl_Armado> tbl_Armado { get; set; }
        public virtual DbSet<Tbl_Bancos> Tbl_Bancos { get; set; }
        public virtual DbSet<tbl_Ciudad> tbl_Ciudad { get; set; }
        public virtual DbSet<tbl_Departamento> tbl_Departamento { get; set; }
        public virtual DbSet<Tbl_Elenco_ENEL> Tbl_Elenco_ENEL { get; set; }
        public virtual DbSet<tbl_Estructura_Material> tbl_Estructura_Material { get; set; }
        public virtual DbSet<tbl_Estructuras> tbl_Estructuras { get; set; }
        public virtual DbSet<Tbl_Grupo_ENEL> Tbl_Grupo_ENEL { get; set; }
        public virtual DbSet<Tbl_Grupo_Zona_ENEL> Tbl_Grupo_Zona_ENEL { get; set; }
        public virtual DbSet<tbl_GrupoTabla> tbl_GrupoTabla { get; set; }
        public virtual DbSet<tbl_GrupoTabla_Detalle> tbl_GrupoTabla_Detalle { get; set; }
        public virtual DbSet<Tbl_Instalacion_CAB_SIGE> Tbl_Instalacion_CAB_SIGE { get; set; }
        public virtual DbSet<tbl_Pais> tbl_Pais { get; set; }
        public virtual DbSet<TBL_Parametros> TBL_Parametros { get; set; }
        public virtual DbSet<Tbl_Personal> Tbl_Personal { get; set; }
        public virtual DbSet<Tbl_Personal_Cargo> Tbl_Personal_Cargo { get; set; }
        public virtual DbSet<tbl_prueba_ubicacion> tbl_prueba_ubicacion { get; set; }
        public virtual DbSet<tbl_SubEstructuras> tbl_SubEstructuras { get; set; }
        public virtual DbSet<tbl_SubTipo_Armado> tbl_SubTipo_Armado { get; set; }
        public virtual DbSet<Tbl_TipoArmado> Tbl_TipoArmado { get; set; }
        public virtual DbSet<Tbl_Zona_ENEL> Tbl_Zona_ENEL { get; set; }
        public virtual DbSet<Tbl_Elenco_Baremo> Tbl_Elenco_Baremo { get; set; }
        public virtual DbSet<Tbl_Elenco_ENEL_Conexiones> Tbl_Elenco_ENEL_Conexiones { get; set; }
        public virtual DbSet<Tbl_Elenco_ENELa> Tbl_Elenco_ENELa { get; set; }
        public virtual DbSet<Tbl_Instalacion_SIGETRAMA> Tbl_Instalacion_SIGETRAMA { get; set; }
        public virtual DbSet<TBL_Recupero_TMP> TBL_Recupero_TMP { get; set; }
        public virtual DbSet<TBL_SED_ZONA> TBL_SED_ZONA { get; set; }
        public virtual DbSet<Tbl_Proveedor> Tbl_Proveedor { get; set; }
        public virtual DbSet<Pub_Monedas> Pub_Monedas { get; set; }
        public virtual DbSet<tbl_Proveedor_Archivos> tbl_Proveedor_Archivos { get; set; }
        public virtual DbSet<tbl_Proveedor_Banco> tbl_Proveedor_Banco { get; set; }
        public virtual DbSet<tbl_TidoDocumento_File> tbl_TidoDocumento_File { get; set; }
        public virtual DbSet<tbl_Proveedor_Evalucion_Cab> tbl_Proveedor_Evalucion_Cab { get; set; }
        public virtual DbSet<tbl_Documento_Archivos> tbl_Documento_Archivos { get; set; }
        public virtual DbSet<tbl_Documento_Cab> tbl_Documento_Cab { get; set; }
        public virtual DbSet<tbl_Documento_Det> tbl_Documento_Det { get; set; }
        public virtual DbSet<tbl_Liquidacion_Caja_Cab> tbl_Liquidacion_Caja_Cab { get; set; }
        public virtual DbSet<tbl_Liquidacion_Caja_Det> tbl_Liquidacion_Caja_Det { get; set; }
        public virtual DbSet<tbl_Proveedor_Evalucion_Det> tbl_Proveedor_Evalucion_Det { get; set; }
        public virtual DbSet<tbl_Proveedor_Incidencia> tbl_Proveedor_Incidencia { get; set; }
    }
}
