//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pub_Monedas
    {
        public string Pub_Empr_Codigo { get; set; }
        public string Pub_Mone_Codigo { get; set; }
        public string Pub_Mone_Descripcion { get; set; }
        public string Pub_Mone_Simbolo { get; set; }
        public string Pub_Mone_Procedencia { get; set; }
        public string Pub_Mone_Uso { get; set; }
        public string Pub_Esta_Codigo { get; set; }
        public string Pub_Mone_UsuCrea { get; set; }
        public Nullable<System.DateTime> Pub_Mone_FecCrea { get; set; }
        public string Pub_Mone_UsuModi { get; set; }
        public Nullable<System.DateTime> Pub_Mone_FecModi { get; set; }
        public string Pub_Mone_Identidad { get; set; }
        public string Pub_Mone_Abreviatura { get; set; }
    }
}
