//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pub_Tipo_Documento
    {
        public string Pub_TiDo_Codigo { get; set; }
        public string Pub_TiDo_Descripcion { get; set; }
        public string Pub_Esta_Codigo { get; set; }
        public string Pub_TiDo_UsuCrea { get; set; }
        public Nullable<System.DateTime> Pub_TiDo_FecCrea { get; set; }
        public string Pub_TiDo_UsuModi { get; set; }
        public Nullable<System.DateTime> Pub_TiDo_FecModi { get; set; }
        public Nullable<int> Pub_TiDo_Identidad { get; set; }
        public string Pub_TiDo_Sunat { get; set; }
        public int id_TipoDocumento { get; set; }
        public string Pub_TiDo_Abreviatura { get; set; }
    }
}
