//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Documento_Det
    {
        public int id_Documento_Det { get; set; }
        public Nullable<int> id_Documento { get; set; }
        public Nullable<int> item_DocDet { get; set; }
        public string alm_Arti_Codigo { get; set; }
        public string Pub_Mone_Codigo { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public Nullable<decimal> cantidad_DocDet { get; set; }
        public Nullable<decimal> precio_DocDet { get; set; }
        public Nullable<decimal> total_DocDet { get; set; }
        public string CtaGastos { get; set; }
        public string CtaIGV { get; set; }
        public string CtaxPagar { get; set; }
        public string Estado { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
