//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Instalacion_SIGETRAMA
    {
        public int id_Instalacion { get; set; }
        public string Contratista { get; set; }
        public string RUC { get; set; }
        public string DES_CONTRATISTA { get; set; }
        public string CONTRATO { get; set; }
        public string TRABAJO { get; set; }
        public string SUBCONTRATISTA { get; set; }
        public string DES_SUBCONTRATISTA { get; set; }
        public string INSPECTOR { get; set; }
        public string DES_INSPECTORES { get; set; }
        public string SUPERV_CONTRA { get; set; }
        public string DES_SUPERV_CONTRA { get; set; }
        public string TRANSACCION { get; set; }
        public string FOLIOSCO { get; set; }
        public string FOLIOSIE { get; set; }
        public string ESTADO { get; set; }
        public string FOLIO_ORIGEN { get; set; }
        public System.DateTime FECHA_DIG { get; set; }
        public string USR_DIG { get; set; }
        public System.DateTime FECHA_APROB { get; set; }
        public string APROBADOR { get; set; }
        public string ORDEN { get; set; }
        public string MATERIAL_SIE { get; set; }
        public decimal CANTIDAD { get; set; }
        public string CONTRATISTA1 { get; set; }
        public decimal VALOR_TRANS { get; set; }
    }
}
