//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Elenco_ENEL_Conexiones
    {
        public string PCon_Orde_Sicot { get; set; }
        public string PCon_Orde_Sicot_Interno { get; set; }
        public string Pub_Sucu_Codigo { get; set; }
        public int idZona { get; set; }
        public string ideLenco { get; set; }
        public int Ele_OPar_Item { get; set; }
        public decimal Ele_OPar_Cantidad { get; set; }
        public decimal Ele_OPar_Precio { get; set; }
        public decimal Ele_OPar_Factor { get; set; }
        public string Pub_Esta_Codigo { get; set; }
        public string PCon_OPar_UsuCrea { get; set; }
        public System.DateTime PCon_OPar_FecCrea { get; set; }
        public string PCon_OPar_UsuModi { get; set; }
        public System.DateTime PCon_OPar_FecModi { get; set; }
    }
}
