//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Proveedor_Banco
    {
        public int id_Proveedor_Banco { get; set; }
        public Nullable<int> id_Proveedor { get; set; }
        public Nullable<int> id_Banco { get; set; }
        public string Pub_Mone_Codigo { get; set; }
        public string id_TipoCuenta { get; set; }
        public string nroCuenta { get; set; }
        public string nroCCI { get; set; }
        public string estado { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
