//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Grupo_Zona_ENEL
    {
        public int idGrupoZona { get; set; }
        public int idGrupo { get; set; }
        public int idZona { get; set; }
        public decimal FactorZona { get; set; }
        public decimal ValorPunto { get; set; }
    }
}
