//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Proveedor_Evalucion_Cab
    {
        public int id_Evaluacion_Cab { get; set; }
        public Nullable<int> id_Proveedor { get; set; }
        public string Ges_Ordt_Codigo { get; set; }
        public Nullable<System.DateTime> fechaEvaluacion_Evaluacion { get; set; }
        public Nullable<System.DateTime> fechaInicial_Evaluacion { get; set; }
        public Nullable<System.DateTime> fechaFinal_Evaluacion { get; set; }
        public string usario_Aprobo { get; set; }
        public Nullable<System.DateTime> fecha_Aprobacion { get; set; }
        public string usuario_Rechazo { get; set; }
        public Nullable<System.DateTime> fecha_Rechazo { get; set; }
        public string Estado { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    }
}
