//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Proveedor
    {
        public int id_Proveedor { get; set; }
        public Nullable<int> id_TipoProveedor { get; set; }
        public Nullable<int> id_TipoPersona { get; set; }
        public string nro_RUC { get; set; }
        public string razonsocial { get; set; }
        public string nombreComercial { get; set; }
        public Nullable<int> vtaProductos { get; set; }
        public Nullable<int> vtaServicios { get; set; }
        public Nullable<int> vtaotros { get; set; }
        public string vtaotrosDetalle { get; set; }
        public string direcion { get; set; }
        public Nullable<int> id_Pais { get; set; }
        public Nullable<int> id_Ciudad { get; set; }
        public Nullable<int> id_Departamento { get; set; }
        public string telefonoFijo { get; set; }
        public string celular { get; set; }
        public string fax { get; set; }
        public string personalContacto_IG { get; set; }
        public string cargo_IG { get; set; }
        public string email_IG { get; set; }
        public string personalContacto_T { get; set; }
        public string cargo_T { get; set; }
        public string email_T { get; set; }
        public string personalContacto_RLC { get; set; }
        public string cargo_RLC { get; set; }
        public Nullable<int> id_TipoDoc_RLC { get; set; }
        public string nro_RLC { get; set; }
        public string email_RLC { get; set; }
        public string nroCuentaDetraccion { get; set; }
        public Nullable<int> check1_UDP { get; set; }
        public Nullable<int> check2_UDP { get; set; }
        public string login_Proveedor { get; set; }
        public string contrasenia_Proveedor { get; set; }
        public string usuario_Aprobo { get; set; }
        public Nullable<System.DateTime> fechaAprobacion { get; set; }
        public string id_MotivoRechazo { get; set; }
        public string descripcionRechazo { get; set; }
        public string usuario_rechazo { get; set; }
        public Nullable<System.DateTime> fechaRechazo { get; set; }
        public string estado { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string celular_T { get; set; }
    }
}
