//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Documento_Archivos
    {
        public int id_Documento_Archivo { get; set; }
        public Nullable<int> id_Documento { get; set; }
        public Nullable<int> id_TipoDocFile { get; set; }
        public string nombreArchivo { get; set; }
        public Nullable<int> nombreArchivo_bd { get; set; }
        public string numeroDocumento { get; set; }
        public Nullable<System.DateTime> fechaDocumento { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string nroSerieDocumento { get; set; }
    }
}
