//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubEstructuras
    {
        public int id_SubEstructura { get; set; }
        public Nullable<int> id_TipoArmado { get; set; }
        public Nullable<int> id_Estructura { get; set; }
        public string Nombre_Estructura { get; set; }
        public string codigo_Estructura { get; set; }
        public string descripcion_Estructura { get; set; }
    }
}
