//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Armado
    {
        public int id_Armado { get; set; }
        public Nullable<int> id_TipoArmado { get; set; }
        public Nullable<int> id_SubTipoArmado { get; set; }
        public string codigo_Armado { get; set; }
        public string descripcion_Armado { get; set; }
        public Nullable<int> id_Estructura { get; set; }
        public string TipoRegistro { get; set; }
        public string Alm_Arti_Codigo { get; set; }
        public Nullable<decimal> Cantidad_Armado { get; set; }
    }
}
