//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Elenco_ENEL
    {
        public string ideLenco { get; set; }
        public string Codigo1 { get; set; }
        public string Codigo2 { get; set; }
        public string Clasificacion1 { get; set; }
        public string Clasificacion2 { get; set; }
        public Nullable<int> idGrupoInstalacion { get; set; }
        public string descripcion { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Puntos { get; set; }
        public Nullable<decimal> ValorPunto { get; set; }
        public string pub_sucu_codigo { get; set; }
    }
}
