//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Recupero_TMP
    {
        public string Matricula { get; set; }
        public string GES_OBRA_CODIGO { get; set; }
        public decimal Almacen { get; set; }
        public decimal devuelto { get; set; }
        public decimal pedido { get; set; }
        public decimal ts { get; set; }
        public decimal tD { get; set; }
        public decimal PorDevolver { get; set; }
    }
}
